# Generated by Django 3.0.6 on 2020-05-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugNumber', models.CharField(max_length=64)),
                ('bugName', models.CharField(max_length=64)),
                ('bugStatus', models.CharField(max_length=16)),
                ('engineerName', models.CharField(max_length=64)),
                ('priority', models.CharField(max_length=16)),
                ('progressStatus', models.CharField(max_length=16)),
                ('userName', models.CharField(max_length=64)),
                ('userEmail', models.CharField(max_length=100)),
                ('userPhoneNumber', models.IntegerField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
