# Generated by Django 3.0.6 on 2020-05-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_bugdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugdetails',
            name='bugNumber',
        ),
        migrations.RemoveField(
            model_name='bugdetails',
            name='bugStatus',
        ),
        migrations.RemoveField(
            model_name='bugdetails',
            name='priority',
        ),
        migrations.AlterField(
            model_name='bugdetails',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bugdetails',
            name='engineerName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='bugdetails',
            name='progressStatus',
            field=models.CharField(default='Open', max_length=16),
        ),
        migrations.AlterField(
            model_name='bugdetails',
            name='userEmail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
