# Generated by Django 3.0.6 on 2020-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200525_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('designation', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='UserTypes',
        ),
    ]
