# Generated by Django 3.0.6 on 2020-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200525_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugdetails',
            name='engineerDesignation',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
