# Generated by Django 3.0.6 on 2020-05-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_bugdetails_engineerdesignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugdetails',
            name='bugName',
            field=models.CharField(max_length=255),
        ),
    ]
